name: Build DroidBlox 32bit

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Extract ZIP
        run: |
          unzip DroidBlox-main.zip
          cp -r DroidBlox-main/* .
          rm -rf DroidBlox-main

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system deps
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip build-essential libffi-dev libssl-dev libjpeg-dev zlib1g-dev libpng-dev libfreetype6-dev pkg-config libcairo2-dev

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install "cython<3"
          sed -i '/^kivy/d' requirements.txt
          sed -i '/^Kivy/d' requirements.txt
          pip install "kivy==2.2.1" "kivymd==1.1.1" pycairo buildozer
          pip install -r requirements.txt

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DroidBlox-APK
          path: bin/*.apk
